name = "Chmy"
uuid = "33a72cf0-4690-46d7-b987-06506c2248b9"
version = "0.2.0"
authors = ["Ivan Utkin <iutkin@ethz.ch> and contributors"]

[workspace]
projects = ["test", "examples"]

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Moshi = "2e0e35c7-a2e4-4343-998d-7ef72827ed2d"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"

[compat]
Adapt = "4"
KernelAbstractions = "0.9"
Moshi = "0.3.12"
OrderedCollections = "2.0.1"
PrettyTables = "3.3.2"
RuntimeGeneratedFunctions = "0.5.26"
julia = "1.12"
